title: Imbricate
application_name: Imbricate
email: info@imbricate.io
description: Imbricate
url: https://imbricate.io
github_username: Imbricate
theme: minima
repository: imbricate/imbricate.io
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
author:
  name: WMXPY
  email: wm@mengw.io
plugins:
  - jekyll-github-metadata
exclude:
  - .jekyll-cache/
  - .vscode/
  - docs/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - makefile
